baseurl: "/"
languageCode: "en-us"
title: "Baptiste Genest website"
author: "Baptiste Genest"
description: "This is the personal webpage of Baptiste Genest."
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"
publishDir: "../../baptiste-genest.github.io"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: About
      url: ""
      weight: 1
    - name: Publications
      url: "publications/"
      weight: 2
    - name: Teaching
      url: "teaching/"
      weight: 3
    - name: Projects
      url: "projects/"
      weight: 4
    - name: Talks
      url: "talks/"
      weight: 5

params:
  description: "Personal webpage of Baptiste Genest."
  footer: "[Github](https://github.com/baptiste-genest) | [Twitter](https://twitter.com/Eulerson314) | Hugo Theme by [Yihui Xie](https://yihui.org/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
